export type { DeepReadonly } from './deep-readonly.js'
export { Opaque } from './opaque.js'
export { Result } from './result.js'
export { Option } from './option.js'
export { getRandomColor } from './get-random-color.js'
export { getRandomFunnyName } from './get-random-name.js'
export { startMeasurement } from './measure.js'
