export type { DeepReadonly } from './deep-readonly'
export { Opaque } from './opaque'
export { Result } from './result'
export { Option } from './option'
export { getRandomColor } from './get-random-color'
export { getRandomFunnyName } from './get-random-name'
export { startMeasurement } from './measure'
